// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use the direct (non-pooled) URL for migrations; runtime queries use
    // the PgBouncer transaction-mode URL set in DATABASE_URL via db.ts
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});

